"""Add quotes module

Revision ID: 2fac928ed4be
Revises: fdff71188918
Create Date: 2026-05-16 21:47:20.481425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fac928ed4be"
down_revision: Union[str, None] = "fdff71188918"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotes",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "quote_number",
            sa.String(length=50),
            nullable=False,
            comment="System-generated quote number (e.g., QTE-20260315)",
        ),
        sa.Column(
            "quote_reference",
            sa.String(length=50),
            nullable=False,
            comment="User-facing quote reference (e.g., QT-0101)",
        ),
        sa.Column(
            "customer_id",
            sa.UUID(),
            nullable=False,
            comment="Customer receiving this quote",
        ),
        sa.Column(
            "transaction_date", sa.Date(), nullable=False, comment="Quote issue date"
        ),
        sa.Column("due_date", sa.Date(), nullable=False, comment="Quote expiry date"),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'draft'"),
            nullable=False,
            comment="Current quote status",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'KES'"),
            nullable=False,
            comment="Quote currency (ISO 4217)",
        ),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="Sum of all line items before discount/tax",
        ),
        sa.Column(
            "discount_type",
            sa.String(length=20),
            nullable=True,
            comment="Type of discount: 'amount' or 'percentage'",
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
            comment="Fixed discount amount (if discount_type = 'amount')",
        ),
        sa.Column(
            "discount_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Discount percentage 0-100 (if discount_type = 'percentage')",
        ),
        sa.Column(
            "tax_total",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="Sum of all tax amounts",
        ),
        sa.Column(
            "total_due",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="Final quote amount: subtotal - discount + tax",
        ),
        sa.Column(
            "rfq_rfp_number",
            sa.String(length=100),
            nullable=True,
            comment="RFQ/RFP reference number",
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="Customer-facing notes/terms (appears on quote)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Last update timestamp",
        ),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When quote was sent to customer",
        ),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When quote was approved",
        ),
        sa.Column(
            "invoiced_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When quote was converted to invoice",
        ),
        sa.Column(
            "expired_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When quote expired (auto-set by scheduled job)",
        ),
        sa.Column(
            "created_by",
            sa.UUID(),
            nullable=True,
            comment="User who created this quote",
        ),
        sa.Column(
            "approved_by",
            sa.UUID(),
            nullable=True,
            comment="User who approved this quote",
        ),
        sa.Column(
            "version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="Version number for optimistic locking",
        ),
        sa.Column(
            "related_invoice_id",
            sa.UUID(),
            nullable=True,
            comment="Invoice created from this quote",
        ),
        sa.CheckConstraint(
            "(discount_type = 'amount' AND discount_percentage IS NULL) OR (discount_type = 'percentage' AND discount_amount IS NULL) OR (discount_type IS NULL AND discount_amount IS NULL AND discount_percentage IS NULL)",
            name=op.f("ck_quotes_ck_quotes_discount_type_consistency"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'sent', 'approved', 'invoiced', 'expired')",
            name=op.f("ck_quotes_ck_quotes_valid_status"),
        ),
        sa.CheckConstraint(
            "due_date >= transaction_date",
            name=op.f("ck_quotes_ck_quotes_due_after_transaction"),
        ),
        sa.CheckConstraint(
            "subtotal >= 0", name=op.f("ck_quotes_ck_quotes_subtotal_non_negative")
        ),
        sa.CheckConstraint(
            "total_due >= 0", name=op.f("ck_quotes_ck_quotes_total_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_quotes_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["related_invoice_id"],
            ["invoices.id"],
            name=op.f("fk_quotes_related_invoice_id_invoices"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotes")),
        sa.UniqueConstraint("quote_number", name="uq_quotes_quote_number"),
    )
    op.create_index("ix_quotes_created_at", "quotes", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_quotes_customer_id"), "quotes", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_quotes_customer_status", "quotes", ["customer_id", "status"], unique=False
    )
    op.create_index(op.f("ix_quotes_due_date"), "quotes", ["due_date"], unique=False)
    op.create_index(
        op.f("ix_quotes_quote_number"), "quotes", ["quote_number"], unique=True
    )
    op.create_index(
        op.f("ix_quotes_quote_reference"), "quotes", ["quote_reference"], unique=False
    )
    op.create_index(
        op.f("ix_quotes_related_invoice_id"),
        "quotes",
        ["related_invoice_id"],
        unique=False,
    )
    op.create_index(op.f("ix_quotes_status"), "quotes", ["status"], unique=False)
    op.create_index(
        "ix_quotes_status_due_date", "quotes", ["status", "due_date"], unique=False
    )
    op.create_index(
        op.f("ix_quotes_transaction_date"), "quotes", ["transaction_date"], unique=False
    )
    op.create_table(
        "quote_line_items",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("quote_id", sa.UUID(), nullable=False),
        sa.Column(
            "line_number",
            sa.Integer(),
            nullable=False,
            comment="Order of line items (1-based)",
        ),
        sa.Column(
            "item_name",
            sa.String(length=500),
            nullable=False,
            comment="Product/service name",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Detailed line item description",
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Quantity of items",
        ),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="Price per unit",
        ),
        sa.Column(
            "line_total",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="Total before tax: quantity × unit_price",
        ),
        sa.Column(
            "tax_type",
            sa.String(length=20),
            nullable=False,
            comment="Tax type for this line",
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="Tax amount for this line",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_total >= 0",
            name=op.f("ck_quote_line_items_ck_quote_line_items_total_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f("ck_quote_line_items_ck_quote_line_items_quantity_positive"),
        ),
        sa.CheckConstraint(
            "tax_amount >= 0",
            name=op.f("ck_quote_line_items_ck_quote_line_items_tax_non_negative"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0",
            name=op.f("ck_quote_line_items_ck_quote_line_items_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
            name=op.f("fk_quote_line_items_quote_id_quotes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_line_items")),
        sa.UniqueConstraint(
            "quote_id", "line_number", name="uq_quote_line_items_quote_line_number"
        ),
    )
    op.create_index(
        op.f("ix_quote_line_items_quote_id"),
        "quote_line_items",
        ["quote_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_customers_fulltext_search"),
        table_name="customers",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_customers_fulltext_search",
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_customers_fulltext_search", table_name="customers", postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_customers_fulltext_search"),
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (((((COALESCE(company_name, ''::character varying)::text || ' '::text) || COALESCE(first_name, ''::character varying)::text) || ' '::text) || COALESCE(last_name, ''::character varying)::text) || ' '::text) || COALESCE(email, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_quote_line_items_quote_id"), table_name="quote_line_items")
    op.drop_table("quote_line_items")
    op.drop_index(op.f("ix_quotes_transaction_date"), table_name="quotes")
    op.drop_index("ix_quotes_status_due_date", table_name="quotes")
    op.drop_index(op.f("ix_quotes_status"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_related_invoice_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_quote_reference"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_quote_number"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_due_date"), table_name="quotes")
    op.drop_index("ix_quotes_customer_status", table_name="quotes")
    op.drop_index(op.f("ix_quotes_customer_id"), table_name="quotes")
    op.drop_index("ix_quotes_created_at", table_name="quotes")
    op.drop_table("quotes")
    # ### end Alembic commands ###
