"""add_quote_reference_unique_constraint_and_invoice_item_name

Revision ID: bda28e6e61fc
Revises: 2fac928ed4be
Create Date: 2026-05-19 08:42:48.390378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda28e6e61fc'
down_revision: Union[str, None] = '2fac928ed4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_fulltext_search'), table_name='customers', postgresql_using='gin')
    op.create_index('ix_customers_fulltext_search', 'customers', [sa.literal_column("to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))")], unique=False, postgresql_using='gin')

    # Add item_name as nullable first so existing rows don't fail
    op.add_column('invoice_line_items', sa.Column('item_name', sa.String(length=500), nullable=True, comment='Product/service name (preserved from quote on conversion)'))

    # Backfill: use the first line of description as item_name for existing rows
    op.execute("""
        UPDATE invoice_line_items
        SET item_name = CASE
            WHEN position(E'\\n' IN description) > 0
            THEN substring(description FROM 1 FOR position(E'\\n' IN description) - 1)
            ELSE description
        END
        WHERE item_name IS NULL
    """)

    # Now enforce NOT NULL
    op.alter_column('invoice_line_items', 'item_name', nullable=False)

    op.create_unique_constraint('uq_quotes_quote_reference', 'quotes', ['quote_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quotes_quote_reference', 'quotes', type_='unique')
    op.drop_column('invoice_line_items', 'item_name')
    op.drop_index('ix_customers_fulltext_search', table_name='customers', postgresql_using='gin')
    op.create_index(op.f('ix_customers_fulltext_search'), 'customers', [sa.literal_column("to_tsvector('english'::regconfig, (((((COALESCE(company_name, ''::character varying)::text || ' '::text) || COALESCE(first_name, ''::character varying)::text) || ' '::text) || COALESCE(last_name, ''::character varying)::text) || ' '::text) || COALESCE(email, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
