"""correct_invoices_module

Revision ID: 0d9abce6f17f
Revises: eb7d085d46e2
Create Date: 2026-05-23 07:38:31.417549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d9abce6f17f"
down_revision: Union[str, None] = "eb7d085d46e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customers_fulltext_search"),
        table_name="customers",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_customers_fulltext_search",
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "vendors",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment=("Primary email address. Unique across non-NULL values"),
        existing_comment="Primary email address. Unique across non-NULL values",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vendors",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Primary email address. Unique across non-NULL values",
        existing_comment=("Primary email address. Unique across non-NULL values"),
        existing_nullable=True,
    )
    op.drop_index(
        "ix_customers_fulltext_search", table_name="customers", postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_customers_fulltext_search"),
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (((((COALESCE(company_name, ''::character varying)::text || ' '::text) || COALESCE(first_name, ''::character varying)::text) || ' '::text) || COALESCE(last_name, ''::character varying)::text) || ' '::text) || COALESCE(email, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
