"""add_invoices_module

Revision ID: eb7d085d46e2
Revises: bda28e6e61fc
Create Date: 2026-05-22 17:50:33.035578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb7d085d46e2"
down_revision: Union[str, None] = "bda28e6e61fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="System-generated vendor UUID",
        ),
        sa.Column(
            "vendor_name",
            sa.String(length=255),
            nullable=False,
            comment="Trading name of the vendor — the only required field",
        ),
        sa.Column(
            "address",
            sa.Text(),
            nullable=True,
            comment="Vendor street / mailing address",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
            comment="Primary email address. Unique across non-NULL values",
        ),
        sa.Column(
            "country",
            sa.String(length=100),
            nullable=True,
            comment="ISO 3166-1 country name or alpha-2 code",
        ),
        sa.Column(
            "phone_primary",
            sa.String(length=30),
            nullable=True,
            comment="Primary phone number with country dialling code prefix",
        ),
        sa.Column(
            "phone_secondary",
            sa.String(length=30),
            nullable=True,
            comment="Secondary phone number with country dialling code prefix",
        ),
        sa.Column(
            "website",
            sa.String(length=500),
            nullable=True,
            comment="Vendor website URL — normalised to include https:// on save",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'KES'"),
            nullable=False,
            comment="Vendor's preferred billing currency. Defaults to the organisation account currency.",
        ),
        sa.Column(
            "vat_number",
            sa.String(length=100),
            nullable=True,
            comment="VAT registration number",
        ),
        sa.Column(
            "tax_id_pin",
            sa.String(length=100),
            nullable=True,
            comment="KRA PIN or equivalent tax ID for the vendor's jurisdiction",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "contact_id",
            sa.UUID(),
            nullable=True,
            comment="Source CRM contact when created via Search Existing Vendor path",
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="Internal notes about this vendor (not shown on documents)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Record creation timestamp. ",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Last update timestamp",
        ),
        sa.Column(
            "created_by",
            sa.UUID(),
            nullable=True,
            comment="UUID of the user who created this vendor record",
        ),
        sa.Column(
            "updated_by",
            sa.UUID(),
            nullable=True,
            comment="UUID of the user who last updated this vendor record",
        ),
        sa.Column(
            "version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="Incremented on every write. Used for optimistic concurrency control.",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')",
            name=op.f("ck_vendors_ck_vendors_valid_status"),
        ),
        sa.CheckConstraint(
            "char_length(trim(vendor_name)) > 0",
            name=op.f("ck_vendors_ck_vendors_name_non_empty"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_index("ix_vendors_contact_id", "vendors", ["contact_id"], unique=False)
    op.create_index("ix_vendors_created_at", "vendors", ["created_at"], unique=False)
    op.create_index("ix_vendors_email", "vendors", ["email"], unique=False)
    op.create_index(op.f("ix_vendors_status"), "vendors", ["status"], unique=False)
    op.create_index(
        "ix_vendors_status_name", "vendors", ["status", "vendor_name"], unique=False
    )
    op.create_index(
        op.f("ix_vendors_vendor_name"), "vendors", ["vendor_name"], unique=False
    )
    op.create_index(
        "uq_vendors_email_not_null",
        "vendors",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "expenses",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "expense_number",
            sa.String(length=50),
            nullable=False,
            comment="Sortable system number e.g. EXP-20260519-001",
        ),
        sa.Column(
            "expense_reference",
            sa.String(length=50),
            nullable=False,
            comment="Short human-facing reference e.g. EXP-0042",
        ),
        sa.Column(
            "vendor_id",
            sa.UUID(),
            nullable=False,
            comment="Vendor this expense is payable to",
        ),
        sa.Column(
            "expense_date",
            sa.Date(),
            nullable=False,
            comment="Date the expense was incurred",
        ),
        sa.Column(
            "due_date",
            sa.Date(),
            nullable=False,
            comment="Payment due date — must be >= expense_date (DB enforced)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="Current lifecycle status",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'KES'"),
            nullable=False,
            comment="ISO 4217 currency — locked after first save",
        ),
        sa.Column(
            "is_recurring",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Recurring-bill flag. Informational only in v1 — no auto-generation.",
        ),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="Σ line_total across all line items",
        ),
        sa.Column(
            "tax_total",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="Σ tax_amount across all line items",
        ),
        sa.Column(
            "total_due",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="subtotal + tax_total (no discount in v1)",
        ),
        sa.Column(
            "amount_paid",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="Cumulative amount recorded via ExpensePayment records",
        ),
        sa.Column(
            "balance_due",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="total_due - amount_paid",
        ),
        sa.Column(
            "notes", sa.Text(), nullable=True, comment="Vendor-facing or internal notes"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "paid_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when expense transitioned to PAID",
        ),
        sa.Column(
            "created_by",
            sa.UUID(),
            nullable=True,
            comment="User who created this expense record",
        ),
        sa.Column(
            "version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="Incremented on every mutating operation — optimistic lock",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'paid', 'overdue')",
            name=op.f("ck_expenses_ck_expenses_valid_status"),
        ),
        sa.CheckConstraint(
            "amount_paid >= 0",
            name=op.f("ck_expenses_ck_expenses_amount_paid_non_negative"),
        ),
        sa.CheckConstraint(
            "balance_due >= 0",
            name=op.f("ck_expenses_ck_expenses_balance_due_non_negative"),
        ),
        sa.CheckConstraint(
            "due_date >= expense_date",
            name=op.f("ck_expenses_ck_expenses_due_after_expense_date"),
        ),
        sa.CheckConstraint(
            "subtotal >= 0", name=op.f("ck_expenses_ck_expenses_subtotal_non_negative")
        ),
        sa.CheckConstraint(
            "tax_total >= 0",
            name=op.f("ck_expenses_ck_expenses_tax_total_non_negative"),
        ),
        sa.CheckConstraint(
            "total_due >= 0",
            name=op.f("ck_expenses_ck_expenses_total_due_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_expenses_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint("expense_number", name="uq_expenses_expense_number"),
        sa.UniqueConstraint("expense_reference", name="uq_expenses_expense_reference"),
    )
    op.create_index("ix_expenses_created_at", "expenses", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_expenses_due_date"), "expenses", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_expense_date"), "expenses", ["expense_date"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_expense_number"), "expenses", ["expense_number"], unique=True
    )
    op.create_index(
        op.f("ix_expenses_expense_reference"),
        "expenses",
        ["expense_reference"],
        unique=True,
    )
    op.create_index(op.f("ix_expenses_status"), "expenses", ["status"], unique=False)
    op.create_index(
        "ix_expenses_status_due_date", "expenses", ["status", "due_date"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_vendor_id"), "expenses", ["vendor_id"], unique=False
    )
    op.create_index(
        "ix_expenses_vendor_status", "expenses", ["vendor_id", "status"], unique=False
    )
    op.create_table(
        "expense_documents",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column(
            "filename",
            sa.String(length=500),
            nullable=False,
            comment="Original filename as uploaded by user",
        ),
        sa.Column(
            "file_size_bytes",
            sa.BigInteger(),
            nullable=False,
            comment="File size in bytes — displayed as KB in UI",
        ),
        sa.Column(
            "mime_type",
            sa.String(length=100),
            nullable=False,
            comment="MIME type for correct Content-Type header on download",
        ),
        sa.Column(
            "storage_key",
            sa.String(length=1000),
            nullable=False,
            comment="Object storage path / key — never exposed in API responses",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            server_default=sa.text("'form'"),
            nullable=False,
            comment="Upload context: form | view | payment_modal",
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "uploaded_by",
            sa.UUID(),
            nullable=True,
            comment="User who attached the document",
        ),
        sa.CheckConstraint(
            "source IN ('form', 'view', 'payment_modal')",
            name=op.f("ck_expense_documents_ck_expense_documents_valid_source"),
        ),
        sa.CheckConstraint(
            "file_size_bytes > 0",
            name=op.f("ck_expense_documents_ck_expense_documents_size_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
            name=op.f("fk_expense_documents_expense_id_expenses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_documents")),
    )
    op.create_index(
        op.f("ix_expense_documents_expense_id"),
        "expense_documents",
        ["expense_id"],
        unique=False,
    )
    op.create_table(
        "expense_line_items",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column(
            "line_number",
            sa.Integer(),
            nullable=False,
            comment="Display order (1-based)",
        ),
        sa.Column(
            "item_name",
            sa.String(length=500),
            nullable=False,
            comment="Product or service name",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Detailed line item description",
        ),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "line_total",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="quantity × unit_price",
        ),
        sa.Column(
            "tax_type",
            sa.String(length=20),
            nullable=False,
            comment="Tax type applied to this line (e.g. vat_16)",
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
            comment="line_total × tax_rate",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_total >= 0",
            name=op.f("ck_expense_line_items_ck_expense_line_items_total_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f("ck_expense_line_items_ck_expense_line_items_quantity_positive"),
        ),
        sa.CheckConstraint(
            "tax_amount >= 0",
            name=op.f("ck_expense_line_items_ck_expense_line_items_tax_non_negative"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0",
            name=op.f("ck_expense_line_items_ck_expense_line_items_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
            name=op.f("fk_expense_line_items_expense_id_expenses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_line_items")),
        sa.UniqueConstraint(
            "expense_id",
            "line_number",
            name="uq_expense_line_items_expense_line_number",
        ),
    )
    op.create_index(
        "ix_expense_line_items_expense_id",
        "expense_line_items",
        ["expense_id"],
        unique=False,
    )
    op.create_table(
        "expense_payments",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column(
            "amount",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="Amount settled in this payment transaction",
        ),
        sa.Column(
            "payment_date",
            sa.Date(),
            nullable=False,
            comment="Date payment was made — required",
        ),
        sa.Column(
            "reference",
            sa.String(length=200),
            nullable=True,
            comment="Transaction ID, cheque number, or remittance reference",
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="Internal notes for this payment entry",
        ),
        sa.Column(
            "document_id",
            sa.UUID(),
            nullable=True,
            comment="Optional proof-of-payment document",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "recorded_by",
            sa.UUID(),
            nullable=True,
            comment="User who recorded this payment",
        ),
        sa.CheckConstraint(
            "amount > 0",
            name=op.f("ck_expense_payments_ck_expense_payments_amount_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["expense_documents.id"],
            name=op.f("fk_expense_payments_document_id_expense_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
            name=op.f("fk_expense_payments_expense_id_expenses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_payments")),
    )
    op.create_index(
        "ix_expense_payments_expense_id",
        "expense_payments",
        ["expense_id"],
        unique=False,
    )
    op.create_index(
        "ix_expense_payments_payment_date",
        "expense_payments",
        ["payment_date"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_customers_fulltext_search"),
        table_name="customers",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_customers_fulltext_search",
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_customers_fulltext_search", table_name="customers", postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_customers_fulltext_search"),
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (((((COALESCE(company_name, ''::character varying)::text || ' '::text) || COALESCE(first_name, ''::character varying)::text) || ' '::text) || COALESCE(last_name, ''::character varying)::text) || ' '::text) || COALESCE(email, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index("ix_expense_payments_payment_date", table_name="expense_payments")
    op.drop_index("ix_expense_payments_expense_id", table_name="expense_payments")
    op.drop_table("expense_payments")
    op.drop_index("ix_expense_line_items_expense_id", table_name="expense_line_items")
    op.drop_table("expense_line_items")
    op.drop_index(
        op.f("ix_expense_documents_expense_id"), table_name="expense_documents"
    )
    op.drop_table("expense_documents")
    op.drop_index("ix_expenses_vendor_status", table_name="expenses")
    op.drop_index(op.f("ix_expenses_vendor_id"), table_name="expenses")
    op.drop_index("ix_expenses_status_due_date", table_name="expenses")
    op.drop_index(op.f("ix_expenses_status"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_expense_reference"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_expense_number"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_expense_date"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_due_date"), table_name="expenses")
    op.drop_index("ix_expenses_created_at", table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(
        "uq_vendors_email_not_null",
        table_name="vendors",
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.drop_index(op.f("ix_vendors_vendor_name"), table_name="vendors")
    op.drop_index("ix_vendors_status_name", table_name="vendors")
    op.drop_index(op.f("ix_vendors_status"), table_name="vendors")
    op.drop_index("ix_vendors_email", table_name="vendors")
    op.drop_index("ix_vendors_created_at", table_name="vendors")
    op.drop_index("ix_vendors_contact_id", table_name="vendors")
    op.drop_table("vendors")
    # ### end Alembic commands ###
