"""correct_invoices_module

Revision ID: 683d60a50164
Revises: 0d9abce6f17f
Create Date: 2026-05-23 11:22:53.132295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "683d60a50164"
down_revision: Union[str, None] = "0d9abce6f17f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customers_fulltext_search"),
        table_name="customers",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_customers_fulltext_search",
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_invoices_invoice_reference"), table_name="invoices")
    op.create_index(
        op.f("ix_invoices_invoice_reference"),
        "invoices",
        ["invoice_reference"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoices_invoice_reference"), table_name="invoices")
    op.create_index(
        op.f("ix_invoices_invoice_reference"),
        "invoices",
        ["invoice_reference"],
        unique=False,
    )
    op.drop_index(
        "ix_customers_fulltext_search", table_name="customers", postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_customers_fulltext_search"),
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (((((COALESCE(company_name, ''::character varying)::text || ' '::text) || COALESCE(first_name, ''::character varying)::text) || ' '::text) || COALESCE(last_name, ''::character varying)::text) || ' '::text) || COALESCE(email, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
