"""add_invoices_module

Revision ID: d11efcf55108
Revises: 3c60966d2a9f
Create Date: 2026-05-15 19:59:08.724824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11efcf55108'
down_revision: Union[str, None] = '3c60966d2a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='System-generated invoice number (e.g., INV-20240707)'),
    sa.Column('invoice_reference', sa.String(length=50), nullable=False, comment='User-facing invoice reference (e.g., IN-0101)'),
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='Customer receiving this invoice'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='Invoice issue date'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='Payment due date'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='Current invoice status'),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'KES'"), nullable=False, comment='Invoice currency (ISO 4217)'),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Sum of all line items before discount/tax'),
    sa.Column('discount_type', sa.String(length=20), nullable=True, comment="Type of discount: 'amount' or 'percentage'"),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment="Fixed discount amount (if discount_type = 'amount')"),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment="Discount percentage 0-100 (if discount_type = 'percentage')"),
    sa.Column('tax_total', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Sum of all tax amounts'),
    sa.Column('total_due', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Final invoice amount: subtotal - discount + tax'),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Total amount paid against this invoice'),
    sa.Column('balance_due', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Remaining balance: total_due - amount_paid'),
    sa.Column('rfq_number', sa.String(length=100), nullable=True, comment='Purchase order or RFQ reference number'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Customer-facing notes (appears on invoice)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Last update timestamp'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='When invoice was sent to customer'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='When invoice was fully paid'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this invoice'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Version number for optimistic locking'),
    sa.CheckConstraint("(discount_type = 'amount' AND discount_percentage IS NULL) OR (discount_type = 'percentage' AND discount_amount IS NULL) OR (discount_type IS NULL AND discount_amount IS NULL AND discount_percentage IS NULL)", name=op.f('ck_invoices_ck_invoices_discount_type_consistency')),
    sa.CheckConstraint("status IN ('draft', 'sent', 'partial', 'paid', 'overdue', 'canceled')", name=op.f('ck_invoices_ck_invoices_valid_status')),
    sa.CheckConstraint('amount_paid >= 0', name=op.f('ck_invoices_ck_invoices_amount_paid_non_negative')),
    sa.CheckConstraint('balance_due >= 0', name=op.f('ck_invoices_ck_invoices_balance_non_negative')),
    sa.CheckConstraint('due_date >= transaction_date', name=op.f('ck_invoices_ck_invoices_due_after_transaction')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_invoices_ck_invoices_subtotal_non_negative')),
    sa.CheckConstraint('total_due >= 0', name=op.f('ck_invoices_ck_invoices_total_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name='uq_invoices_invoice_number')
    )
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_invoices_customer_status', 'invoices', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_invoice_reference'), 'invoices', ['invoice_reference'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_status_due_date', 'invoices', ['status', 'due_date'], unique=False)
    op.create_index(op.f('ix_invoices_transaction_date'), 'invoices', ['transaction_date'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False, comment='Order of line items (1-based)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Line item description'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Quantity of items'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Price per unit'),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total before tax: quantity × unit_price'),
    sa.Column('tax_type', sa.String(length=20), nullable=False, comment='Tax type for this line'),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Tax amount for this line'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_invoice_line_items_ck_line_items_total_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_invoice_line_items_ck_line_items_quantity_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_invoice_line_items_ck_line_items_tax_non_negative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_invoice_line_items_ck_line_items_price_non_negative')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items')),
    sa.UniqueConstraint('invoice_id', 'line_number', name='uq_line_items_invoice_line_number')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_index('ix_line_items_invoice_id', 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Payment amount'),
    sa.Column('payment_date', sa.Date(), nullable=False, comment='Date payment was received'),
    sa.Column('payment_method', sa.String(length=30), nullable=False, comment='Payment method used'),
    sa.Column('reference', sa.String(length=200), nullable=True, comment='Payment reference (check number, transaction ID, etc.)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about this payment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True, comment='User who recorded this payment'),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.drop_index(op.f('ix_customers_fulltext_search'), table_name='customers', postgresql_using='gin')
    op.create_index('ix_customers_fulltext_search', 'customers', [sa.literal_column("to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_fulltext_search', table_name='customers', postgresql_using='gin')
    op.create_index(op.f('ix_customers_fulltext_search'), 'customers', [sa.literal_column("to_tsvector('english'::regconfig, (((((COALESCE(company_name, ''::character varying)::text || ' '::text) || COALESCE(first_name, ''::character varying)::text) || ' '::text) || COALESCE(last_name, ''::character varying)::text) || ' '::text) || COALESCE(email, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_line_items_invoice_id', table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_invoices_transaction_date'), table_name='invoices')
    op.drop_index('ix_invoices_status_due_date', table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_reference'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index('ix_invoices_customer_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
