"""add_customer_indexes

Revision ID: 7d2461c6487d
Revises: 0001_initial
Create Date: 2026-05-14 12:14:04.991967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d2461c6487d'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pg_trgm extension for text search/GIN indexes
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('customers', 'customer_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Customer type: individual or business',
               existing_nullable=False)
    op.alter_column('customers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'"),
               comment='Customer account status',
               existing_nullable=False)
    op.alter_column('customers', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Company name for business customers',
               existing_nullable=True)
    op.alter_column('customers', 'vat_number',
               existing_type=sa.VARCHAR(length=50),
               comment='VAT/Tax registration number',
               existing_nullable=True)
    op.alter_column('customers', 'website',
               existing_type=sa.VARCHAR(length=500),
               comment='Company website URL',
               existing_nullable=True)
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Contact person first name',
               existing_nullable=False)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Contact person last name',
               existing_nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Primary email address',
               existing_nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Primary phone number',
               existing_nullable=False)
    op.alter_column('customers', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'KES'"),
               type_=sa.String(length=3),
               comment='Default currency for transactions',
               existing_nullable=False)
    op.alter_column('customers', 'balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               type_=sa.Numeric(precision=15, scale=2),
               comment='Current account balance',
               existing_nullable=False)
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               comment='Primary address line',
               existing_nullable=False)
    op.alter_column('customers', 'address2',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               comment='Secondary address line',
               existing_nullable=True)
    op.alter_column('customers', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City',
               existing_nullable=False)
    op.alter_column('customers', 'province',
               existing_type=sa.VARCHAR(length=100),
               comment='State/Province/Region',
               existing_nullable=False)
    op.alter_column('customers', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Postal/ZIP code',
               existing_nullable=False)
    op.alter_column('customers', 'country',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               comment='ISO 3166-1 alpha-2 country code',
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False,
               comment='Record creation timestamp')
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False,
               comment='Record last update timestamp')
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_customers_country'), 'customers', ['country'], unique=False)
    op.create_index(op.f('ix_customers_customer_type'), 'customers', ['customer_type'], unique=False)
    op.create_index(op.f('ix_customers_first_name'), 'customers', ['first_name'], unique=False)
    op.create_index('ix_customers_fulltext_search', 'customers', [sa.literal_column("to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_customers_last_name'), 'customers', ['last_name'], unique=False)
    op.create_index('ix_customers_search', 'customers', ['first_name', 'last_name', 'company_name'], unique=False, postgresql_using='gin', postgresql_ops={'first_name': 'gin_trgm_ops', 'last_name': 'gin_trgm_ops', 'company_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_index('ix_customers_status_created', 'customers', ['status', 'created_at'], unique=False)
    op.create_index('ix_customers_type_status', 'customers', ['customer_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_type_status', table_name='customers')
    op.drop_index('ix_customers_status_created', table_name='customers')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index('ix_customers_search', table_name='customers', postgresql_using='gin', postgresql_ops={'first_name': 'gin_trgm_ops', 'last_name': 'gin_trgm_ops', 'company_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_customers_last_name'), table_name='customers')
    op.drop_index('ix_customers_fulltext_search', table_name='customers', postgresql_using='gin')
    op.drop_index(op.f('ix_customers_first_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_country'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True,
               comment=None,
               existing_comment='Record last update timestamp')
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp')
    op.alter_column('customers', 'country',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='ISO 3166-1 alpha-2 country code',
               existing_nullable=False)
    op.alter_column('customers', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Postal/ZIP code',
               existing_nullable=False)
    op.alter_column('customers', 'province',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='State/Province/Region',
               existing_nullable=False)
    op.alter_column('customers', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='City',
               existing_nullable=False)
    op.alter_column('customers', 'address2',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Secondary address line',
               existing_nullable=True)
    op.alter_column('customers', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Primary address line',
               existing_nullable=False)
    op.alter_column('customers', 'balance',
               existing_type=sa.Numeric(precision=15, scale=2),
               server_default=None,
               type_=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Current account balance',
               existing_nullable=False)
    op.alter_column('customers', 'currency',
               existing_type=sa.String(length=3),
               server_default=None,
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Default currency for transactions',
               existing_nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Primary phone number',
               existing_nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Primary email address',
               existing_nullable=False)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Contact person last name',
               existing_nullable=False)
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Contact person first name',
               existing_nullable=False)
    op.alter_column('customers', 'website',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Company website URL',
               existing_nullable=True)
    op.alter_column('customers', 'vat_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='VAT/Tax registration number',
               existing_nullable=True)
    op.alter_column('customers', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Company name for business customers',
               existing_nullable=True)
    op.alter_column('customers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment=None,
               existing_comment='Customer account status',
               existing_nullable=False)
    op.alter_column('customers', 'customer_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Customer type: individual or business',
               existing_nullable=False)
    op.alter_column('customers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
