"""make_address_fields_nullable

Revision ID: 25134e7109ca
Revises: 7d2461c6487d
Create Date: 2026-05-14 14:27:20.639150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25134e7109ca"
down_revision: Union[str, None] = "7d2461c6487d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customers",
        "address",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_comment="Primary address line",
    )
    op.alter_column(
        "customers",
        "city",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_comment="City",
    )
    op.alter_column(
        "customers",
        "province",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_comment="State/Province/Region",
    )
    op.alter_column(
        "customers",
        "postal_code",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_comment="Postal/ZIP code",
    )
    op.alter_column(
        "customers",
        "country",
        existing_type=sa.VARCHAR(length=2),
        nullable=True,
        existing_comment="ISO 3166-1 alpha-2 country code",
    )
    op.drop_index(
        op.f("ix_customers_fulltext_search"),
        table_name="customers",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_customers_fulltext_search",
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_customers_fulltext_search", table_name="customers", postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_customers_fulltext_search"),
        "customers",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (((((COALESCE(company_name, ''::character varying)::text || ' '::text) || COALESCE(first_name, ''::character varying)::text) || ' '::text) || COALESCE(last_name, ''::character varying)::text) || ' '::text) || COALESCE(email, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "customers",
        "country",
        existing_type=sa.VARCHAR(length=2),
        nullable=False,
        existing_comment="ISO 3166-1 alpha-2 country code",
    )
    op.alter_column(
        "customers",
        "postal_code",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_comment="Postal/ZIP code",
    )
    op.alter_column(
        "customers",
        "province",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_comment="State/Province/Region",
    )
    op.alter_column(
        "customers",
        "city",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_comment="City",
    )
    op.alter_column(
        "customers",
        "address",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_comment="Primary address line",
    )
    # ### end Alembic commands ###
