"""add quotes models

Revision ID: fdff71188918
Revises: d11efcf55108
Create Date: 2026-05-16 21:36:38.669921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdff71188918'
down_revision: Union[str, None] = 'd11efcf55108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_fulltext_search'), table_name='customers', postgresql_using='gin')
    op.create_index('ix_customers_fulltext_search', 'customers', [sa.literal_column("to_tsvector('english', coalesce(company_name, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_fulltext_search', table_name='customers', postgresql_using='gin')
    op.create_index(op.f('ix_customers_fulltext_search'), 'customers', [sa.literal_column("to_tsvector('english'::regconfig, (((((COALESCE(company_name, ''::character varying)::text || ' '::text) || COALESCE(first_name, ''::character varying)::text) || ' '::text) || COALESCE(last_name, ''::character varying)::text) || ' '::text) || COALESCE(email, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
