import { COMPANY_INFO } from "@/constants";
import { formatCurrency, formatDisplayDate } from "@/lib/utils";
import { Image as ImageIcon } from "lucide-react";

export interface DocumentViewerData {
    documentReference?: string;
    customerId?: string;
    customer?: {
        display_name: string;
        email: string;
        phone: string;
        address?: string;
    };
    transactionDate?: string;
    dueDate?: string;
    currency?: string;
    rfqNumber?: string;
    notes?: string;
    discountType?: "amount" | "percentage" | null;
    discountAmount?: number | null;
    discountPercentage?: number | null;
    subtotal: number;
    taxTotal: number;
    totalDue: number;
    amountPaid?: number;
    balanceDue?: number;
    lineItems: {
        id: string;
        itemName?: string;
        description: string;
        quantity: number;
        unitPrice: number;
        taxType?: string;
        lineTotal: number;
    }[];
}

interface DocumentViewerProps {
    type: "invoice" | "quote";
    data: DocumentViewerData;
}

export function DocumentViewer({ type, data }: Readonly<DocumentViewerProps>) {
    const isInvoice = type === "invoice";
    const label = isInvoice ? "INVOICE" : "QUOTE";

    const vatTypes = Array.from(new Set(data.lineItems.map(item => item.taxType).filter(t => t && t.startsWith("vat_"))));
    let vatLabel = "VAT";
    if (vatTypes.length === 1 && vatTypes[0]) {
        const rate = vatTypes[0].split("_")[1];
        if (rate) vatLabel = `VAT (${rate}%)`;
    } else if (vatTypes.length > 1) {
        vatLabel = "VAT (Mixed)";
    }

    return (
        <div className="bg-white rounded-[20px] border-2 border-purple-25 overflow-hidden">
            {/* Top Section */}
            <div className="p-6">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {/* Logo Column */}
                    <div className="flex flex-col items-start gap-3">
                        <div className="w-16 h-16 bg-gray-100 rounded-lg flex items-center justify-center border border-gray-200 text-gray-500">
                            <ImageIcon size={28} />
                        </div>
                    </div>

                    {/* Company Info */}
                    <div className="flex flex-col gap-1 text-gray-800">
                        <h3 className="font-bold text-base mb-1">{COMPANY_INFO.name}</h3>
                        <p className="text-sm">{COMPANY_INFO.address}</p>
                        <p className="text-sm">{COMPANY_INFO.phone}</p>
                        <p className="text-sm mb-1">{COMPANY_INFO.email}</p>
                    </div>

                    {/* Document To */}
                    <div className="flex flex-col gap-1">
                        <h2 className="text-[22px] font-black text-gray-800 tracking-wider mb-1 uppercase">{label}</h2>
                        <p className="text-sm text-gray-500 mb-1">To</p>

                        <div className="flex flex-col gap-1">
                            <p className="text-[16px] font-bold text-priori-purple">{data.customer?.display_name || data.customerId}</p>
                            {data.customer && (
                                <>
                                    {data.customer.address && (
                                        <p className="text-sm text-gray-600">{data.customer.address}</p>
                                    )}
                                    <p className="text-sm text-gray-600">{data.customer.phone}</p>
                                    <p className="text-sm text-gray-600">{data.customer.email}</p>
                                </>
                            )}
                        </div>
                    </div>
                </div>
            </div>

            {/* Metadata Row */}
            <div className="p-6 gap-6">
                <div className="grid grid-cols-2 md:grid-cols-10 gap-6">
                    <div className="flex flex-col gap-2 md:col-span-2">
                        <label className="text-gray-500 font-medium w-full">Reference</label>
                        <p className="font-bold text-gray-800">{data.documentReference || "Autogenerated"}</p>
                    </div>

                    <div className="flex flex-col gap-2 md:col-span-2">
                        <label className="text-gray-500 font-medium w-full">Transaction Date</label>
                        <span className="font-bold text-gray-800 whitespace-nowrap">
                            {data.transactionDate ? formatDisplayDate(data.transactionDate) : "-"}
                        </span>
                    </div>

                    <div className="flex flex-col gap-2 md:col-span-2">
                        <label className="text-gray-500 font-medium w-full">Due Date</label>
                        <span className="font-bold text-gray-800 whitespace-nowrap">
                            {data.dueDate ? formatDisplayDate(data.dueDate) : "-"}
                        </span>
                    </div>

                    <div className="flex flex-col gap-2 min-w-0 md:col-span-3">
                        <label className="text-gray-500 font-medium w-full">RFQ/RFP Number</label>
                        <span className="font-bold text-gray-800 truncate block">{data.rfqNumber || '-'}</span>
                    </div>

                    <div className="flex flex-col gap-2 md:col-span-1">
                        <label className="text-gray-500 font-medium w-full">Currency</label>
                        <span className="font-bold text-gray-800 whitespace-nowrap">{data.currency}</span>
                    </div>
                </div>
            </div>

            <div className="h-px bg-purple-25 w-full" />

            {/* Line Items */}
            <div className="p-6 flex flex-col gap-6">
                <h3 className="text-[20px] leading-7.5 font-bold text-gray-800">Item Details</h3>

                <div className="flex flex-col gap-3 overflow-x-auto pb-4">
                    <table className="w-full text-[16px] min-w-[800px]">
                        <thead>
                            <tr className="bg-priori-purple text-white px-3 py-4 first:rounded-tl-lg last:rounded-tr-lg grid grid-cols-7">
                                <th className="text-left px-3 font-bold leading-8 col-span-4">Item</th>
                                <th className="text-center px-3 font-bold leading-8">Quantity</th>
                                <th className="text-center px-3 font-bold leading-8">Price</th>
                                <th className="text-center px-3 font-bold leading-8">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data.lineItems.map(item => (
                                <tr key={item.id} className="group relative mb-3 grid grid-cols-7 gap-4 pt-2">
                                    <td className="align-left col-span-4">
                                        <p className="w-full bg-transparent px-3 py-4 text-gray-800 flex flex-col gap-2">
                                            <span className="font-bold">
                                                {item.itemName || item.description.split('\n')[0] || ""}
                                            </span>
                                            <span className="font-normal whitespace-pre-wrap">
                                                {item.description}
                                            </span>
                                        </p>
                                    </td>
                                    <td className="align-top">
                                        <p className="w-full bg-transparent px-3 py-4 text-gray-800 text-center">
                                            {item.quantity}
                                        </p>
                                    </td>
                                    <td className="align-top">
                                        <p className="w-full bg-transparent px-3 py-4 text-gray-800 text-right">
                                            {formatCurrency(item.unitPrice, "")}
                                        </p>
                                    </td>
                                    <td className="align-top">
                                        <p className="w-full bg-transparent px-3 py-4 text-gray-800 text-right font-medium">
                                            {formatCurrency(item.lineTotal, "")}
                                        </p>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>

                    {/* Subtotals */}
                    <div className="w-full flex justify-end mt-4">
                        <div className="min-w-80 flex flex-col gap-4 text-gray-800">
                            {/* Subtotal */}
                            <div className="flex justify-between items-center font-bold">
                                <span>Subtotal</span>
                                <span>{formatCurrency(data.subtotal, data.currency || "")}</span>
                            </div>

                            {data.discountType && (
                                <div className="flex justify-between items-center text-sm text-gray-600">
                                    <span className="font-bold">Discount {data.discountType === "percentage" ? `(${data.discountPercentage}%)` : ""}</span>
                                    <span className="font-medium text-red-500">-{formatCurrency(data.discountAmount ?? 0, data.currency || "")}</span>
                                </div>
                            )}

                            <div className="h-px bg-purple-25 w-full opacity-50" />

                            {/* VAT Row */}
                            <div className="flex justify-between items-center text-gray-800">
                                <span>{vatLabel}</span>
                                <span>{formatCurrency(data.taxTotal, data.currency || "")}</span>
                            </div>

                            <div className="h-px bg-purple-25 w-full opacity-50" />

                            {/* Total Due */}
                            <div className="flex justify-between items-center font-bold text-[16px] text-gray-900 mt-1">
                                <span>Total Due</span>
                                <span>{formatCurrency(data.totalDue, data.currency || "")}</span>
                            </div>

                            {(data.amountPaid ?? 0) > 0 && (
                                <>
                                    <div className="h-px bg-purple-25 w-full opacity-50" />
                                    <div className="flex justify-between items-center font-bold text-[16px] text-gray-900 mt-1">
                                        <span>Amount Paid</span>
                                        <span>{formatCurrency(data.amountPaid ?? 0, data.currency || "")}</span>
                                    </div>
                                    <div className="flex justify-between items-center font-bold text-[16px] text-gray-900 mt-1">
                                        <span>Balance Due</span>
                                        <span>{formatCurrency(data.balanceDue ?? 0, data.currency || "")}</span>
                                    </div>
                                </>
                            )}
                        </div>
                    </div>
                </div>
            </div>

            {/* Notes */}
            <div className="p-8 pt-6">
                <label className="block text-[16px] font-bold text-gray-800 mb-3">Notes</label>
                <div className="w-full px-3 py-4 text-[16px] rounded-xl min-h-[100px] whitespace-pre-wrap">
                    {data.notes || "No notes added."}
                </div>
            </div>
        </div>
    );
}
