"""Structural invariants for the ORM schema.

These checks run purely against the in-memory SQLAlchemy ``MetaData`` (no
database connection), so they execute fast and deterministically before any
DB-backed test. They guard the whole model layer from a single place rather
than relying on per-model review.
"""

from collections import Counter

import pytest

# Importing the package registers every model on the shared Base.metadata.
import app.main  # noqa: F401  (import for its model-registration side effect)
from app.common.database import Base

# Pure in-memory metadata check: must not depend on a live database, so opt
# out of the autouse setup_db fixture (whose create_all would otherwise fail
# first and mask this assertion).
pytestmark = pytest.mark.no_db


def _index_names() -> list[str]:
    """Every index name declared across all mapped tables.

    Covers both explicit ``Index(...)`` entries in ``__table_args__`` and the
    implicit indexes generated by ``mapped_column(..., index=True)``.
    """
    names = []
    for table in Base.metadata.tables.values():
        for constraint in table.constraints:
            if constraint.name:
                names.append(constraint.name)
    return names


def test_index_names_are_unique() -> None:
    """No two indexes may share a name.

    PostgreSQL index names are schema-global, and ``create_all`` emits one
    ``CREATE INDEX`` per declared index. A duplicate name (e.g. a column
    ``index=True`` colliding with an explicit same-named ``Index()``) makes
    the second statement fail with ``DuplicateTable``. Fail here, with the
    offending names, instead of deep inside a Postgres test run.
    """
    duplicates = sorted(
        name for name, count in Counter(_index_names()).items() if count > 1
    )
    assert not duplicates, (
        "Duplicate index name(s) declared across models: "
        f"{duplicates}. Each index name must be unique; remove the redundant "
        "column-level index=True or the duplicate Index() in __table_args__."
    )
